using DCP_Accounts_Api.Models;
using Microsoft.EntityFrameworkCore;

namespace DCP_Accounts_Api.Data
{
    public class AppDbContext : DbContext
    {
        public AppDbContext(DbContextOptions<AppDbContext> options) : base(options) { }

        public DbSet<Expend> Expends { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Expend>(entity =>
            {
                entity.ToTable("tblExpend");

                // PK is provided by the client (NOT identity / NOT generated by DB)
                entity.HasKey(e => e.ExpenditurID);
                entity.Property(e => e.ExpenditurID).ValueGeneratedNever();  // <-- KEY FIX

                // Column shapes to match your SQL table
                entity.Property(e => e.ExpSubCode)
                      .HasMaxLength(4)      // char(4)
                      .IsRequired();

                entity.Property(e => e.UID)
                      .HasMaxLength(5)      // varchar(5)
                      .IsRequired();

                entity.Property(e => e.ExpDate)
                      .HasColumnType("date")
                      .IsRequired();

                entity.Property(e => e.EntryDate)
                      .HasColumnType("datetime"); // nullable is fine
            });

            base.OnModelCreating(modelBuilder);
        }
    }
}
